site_name: 'Microsoft - CSS-Exchange'
docs_dir: 'docs'
nav:
  - Emerging Issues: Emerging-Issues.md
  - Admin:
    - Clear-MailboxPermission: Admin/Clear-MailboxPermission.md
    - Get-SimpleAuditLogReport: Admin/Get-SimpleAuditLogReport.md
    - Test-AMSI: Admin/Test-AMSI.md
  - Databases:
    - VSSTester: Databases/VSSTester.md
  - Diagnostics:
    - ExchangeLogCollector: Diagnostics/ExchangeLogCollector.md
    - ExTRA: Diagnostics/ExTRA.md
    - HealthChecker:
      - Diagnostics/HealthChecker/index.md
      - AMSICheck: Diagnostics/HealthChecker/AMSIIntegration.md
      - CertificateCheck: Diagnostics/HealthChecker/CertificateCheck.md
      - LMCompatibilityLevelInformationCheck: Diagnostics/HealthChecker/LMCompatibilityLevelInformationCheck.md
      - RebootPending: Diagnostics/HealthChecker/RebootPending.md
      - SMBv1Check: Diagnostics/HealthChecker/SMBv1Check.md
      - TLSConfigurationCheck: Diagnostics/HealthChecker/TLSConfigurationCheck.md
      - VulnerabilityCheck: Diagnostics/HealthChecker/VulnerabilityCheck.md
    - Test-ExchAVExclusions: Diagnostics/Test-ExchAVExclusions.md
  - Hybrid:
    - Test-HMAEAS: Hybrid/Test-HMAEAS.md
  - M365:
    - DLT365Groupsupgrade: M365/DLT365Groupsupgrade.md
  - Performance:
    - ExPerfAnalyzer: Performance/ExPerfAnalyzer.md
    - SimplePerf: Performance/SimplePerf.md
  - PublicFolders:
    - SourceSideValidations: PublicFolders/SourceSideValidations.md
    - ValidateMailEnabledPublicFolders: PublicFolders/ValidateMailEnabledPublicFolders.md
  - Retention:
    - Get-MRMDetails: Retention/Get-MRMDetails.md
  - Search:
    - Troubleshoot-ModernSearch: Search/Troubleshoot-ModernSearch.md
  - Security:
    - EOMT: Security/EOMT.md
    - ExchangeMitigations: Security/ExchangeMitigations.md
    - Test-CVE-2021-34470: Security/Test-CVE-2021-34470.md
    - Test-ProxyLogon: Security/Test-ProxyLogon.md
  - Setup:
    - CopyMissingDlls: Setup/CopyMissingDlls.md
    - FixInstallerCache: Setup/FixInstallerCache.md
    - SetupAssist:
      - Setup/SetupAssist/index.md
      - ComputersContainer: Setup/SetupAssist/ComputersContainer.md
      - ReadOnlyDomainControllerContainer: Setup/SetupAssist/ReadOnlyDomainControllerContainer.md
      - RebootPending: Setup/SetupAssist/RebootPending.md
    - SetupLogReviewer: Setup/SetupLogReviewer.md
theme:
  name: 'material'
  features:
    - navigation.indexes
repo_url: https://github.com/microsoft/CSS-Exchange
site_url: https://microsoft.github.io/CSS-Exchange
