name: Limit Pull Requests

on:
  pull_request:
    branches:
      - release

jobs:
  limit_release_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: LukBukkit/action-pr-limits@v1.2.0
        with:
          allowlist: |
            main
